CREATE TABLE IF NOT EXISTS work_item
(
   work_item_id   INTEGER PRIMARY KEY,
   work_item_name VARCHAR(20) NOT NULL
);

DELETE FROM work_item;

INSERT INTO work_item(work_item_id, work_item_name) VALUES (1, '1');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (2, '2');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (3, '3');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (4, '4');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (5, '5');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (6, '6');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (7, '7');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (8, '8');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (9, '9');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (10, '10');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (11, '11');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (12, '12');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (13, '13');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (14, '14');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (15, '15');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (16, '16');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (17, '17');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (18, '18');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (19, '19');
INSERT INTO work_item(work_item_id, work_item_name) VALUES (20, '20');

CREATE TABLE IF NOT EXISTS work_log
(
   work_log_id      INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
   work_item_id     INTEGER,
   work_log_message VARCHAR(200)
);

DELETE FROM work_log;
